### ISSUE TITLE
Cannot confirm BAT supply transaction through Metamask

### ISSUE THREAD

**Issue by ahadda5** [compound-finance/compound-protocol#102]
I cannot supply my BATs to the compound layer. 

1) metamask Mainnet is connected and shows the BAT balance. 
2) I connect it to app.compound  ( i have Brave browser but it is disabled for this site - its guard is down )
3) I try to supply BAT however the confirm button is always greyed out. 

![bat compound](https://user-images.githubusercontent.com/21275079/108180555-5aba8f00-7120-11eb-9fe8-a73197a99bdd.JPG)

**Comment by ahadda5** [comment]
this seems to be a metamask issue

**Comment by 813TEK** [comment]
What kind of a Dick just closes a support question by pulling some
governmental bullshit like that? "Oh well its not our problem, closed"
like...fuck yourself, I now habe 0 support for the compound protocol if
thats they way you treat people who want to believe in your shithead
moderated system. Ill take my money elsewhere.. Maybe where support does
that thing for clients... Umm.. Support!
