### ISSUE TITLE
Compatibility Issues with Linux

### ISSUE THREAD

**Issue by amanullah69** [compound-finance/compound-protocol#106]
Hi, I'm facing several error while deploying contracts. Kindly help me to solve these. Which commit is stable one?

-> Compatibility issues when run running yarn deploy.
Getting scenario packages...
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.

-> When running this command "yarn repl -n rinkeby", I got this error.
$ ./scenario/script/repl -n rinkeby
Skipping Scenario Rebuild (set rebuild=true to force)
Compiling Solidity contracts...
Compiling contracts {contracts,contracts/**,tests/Contracts}/*.sol with solc to /home/aman/Aman/selenium/compound-protocol/.build/contracts.json...
SyntaxError: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
undefined
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by rleshner** [comment]
For questions, please visit the Compound [Discord](https://compound.finance/discord).
