### ISSUE TITLE
Please open source the api backend. Or at list the liquidation part of it

### ISSUE THREAD

**Issue by ytrezq** [compound-finance/compound-protocol#131]
Might not be the right repository to ask this, but would it be possible to open source the backend for the liquidation api? I m having enhancement ideas. But how to get a list of borrowers from a full archival node as fast as the api does is definitely not trivial.

**Comment by mspaansen** [comment]
Ok

**Comment by ytrezq** [comment]
@rleshner why did you closed this? Please reopen!
