### ISSUE TITLE
withdraw `type(uint256).max` will not affect usdc pool balance

### ISSUE THREAD

**Issue by alan890104** [compound-finance/compound-protocol#237]
## Reproduce (on block height `17228670`)
1. alice apply 1000 USDC to compound
2. Bob supply 200,000 WETH to compound
3. bob borrows all of the usdc from compound. However, when I fill in `type(uint256).max` instead of `usdc.balanceOf(address(compound))`, the balance of usdc in compound does not change.

[This line in my code](https://github.com/alan890104/311551044-bdaf-lab7/blob/0ca7b6762bbcf434a69dd622879369d41ed78c26/test/lab7.t.sol#LL71C8-L72C77) is the place where error occurs.

The document says `A value of MaxUint256 will withdraw all of the src’s base balance.`
![image](https://github.com/compound-finance/compound-protocol/assets/48343225/f847649b-d3b3-4581-b127-6fac14d73d14)

**Comment by kevincheng96** [comment]
Just an FYI, the documentation you are referring to is for v3 but this repo is for v2. The v3 repo can be found [here](https://github.com/compound-finance/comet).

Your test is behaving as expected for v3. Using `MaxUint256` as the amount for `withdraw` will withdraw all of the user's base balance (the amount of USDC supplied). In this case, Bob has not supplied any USDC so his base balance is 0.

**Comment by alan890104** [comment]
Greatly appreciate your explanation!
