### ISSUE TITLE
approve ffffff in app.compound.finance is risky

### ISSUE THREAD

**Issue by jtomtan** [compound-finance/compound-protocol#27]
Hi, 

I am from Ownbit [https://ownbit.io] wallet team, and we are integrating with Compound protocol. When we tried to use https://app.compound.finance/ we found the approve function is passing fffffff as the amount which we thing may lead to future problems.

Function: approve(address _spender, uint256 _value)
​
MethodID: 0x095ea7b3
[0]:  000000000000000000000000f650c3d88d12db855b8bf7d11be6c55a4e07dcc9
[1]:  ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

Take USDT for example, this call will make cUSDT contract has the ability to transfer all tokens in my account now and in future. This is unnecessary and risky.

**Comment by jflatow** [comment]
This is not an appropriate issue for this repository
