### ISSUE TITLE
Ledger Confirmation

### ISSUE THREAD

**Issue by Jason7124** [compound-finance/compound-protocol#43]
I tried using the app today to supply some USDT and withdrawl some ETH  Both time it will let me confirm on ly Nano S but the app doesn't see that confirmation and just waits indefinetly.  Any Ideas

**Comment by hayesgm** [comment]
Thanks for reaching out. The best way to get help on this issue would be to bring it up on [Discord](https://compound.finance/discord). We're happy to help there. This repo and issue system should only be in reference to upgrades and questions about the protocol code itself.
