### ISSUE TITLE
Testing comptroller on Rinkeby

### ISSUE THREAD

**Issue by buendiadas** [compound-finance/compound-protocol#44]
Testing an integration with `COMP` from an external contract I wanted to make use of the `claimComp(address)` function. 

However, the Comptroller address provided at the documentation [0x2eaa9d77ae4d8f9cdd9faacd44016e746485bddb](https://rinkeby.etherscan.io/address/0x2eaa9d77ae4d8f9cdd9faacd44016e746485bddb#code) looks outdated. 

Is the latest version of Comptroller available at any testnet? Otherwise, could this be updated?

**Comment by Pet3ris** [comment]
Hi @buendiadas, that is still the right address listed in https://compound.finance/docs. We recently tested on it for the grant proposal.

Just a guess - if you're trying to use Etherscan to run `claimComp`, you may not be able to as the proxy contract hasn't been configured. If you use an alternative tool like MEW (MyEtherWallet), it should work better.

**Comment by buendiadas** [comment]
Thanks that was probably the case
