### ISSUE TITLE
'shasum -p' option only works on MacOS and Ubuntu, not work on Debian GNU/Linux 10 (buster)

### ISSUE THREAD

**Issue by FinnZhang** [compound-finance/compound-protocol#60]
The scripts contains 'shasum -p' don't work, when I run the bash scripts in script directory on Debian.
The output is:
$ yarn coverage
yarn run v1.22.4
$ ./script/coverage
Unknown option: p
Type shasum -h for help
Unknown option: p
Type shasum -h for help

Just drop the '-p' option can fix the problem on Debian.

**Comment by lancefrench** [comment]
The difference here stems from `shasum` version 6+ on Debian Buster versus versions older than 6 on Mac OS Catalina, etc.  This will break for those who have upgraded to Mac OS Big Sur as it now includes `6.01`.

If needed, the `-p` option is now replaced with `-U` for "Universal Newlines Mode."

**Comment by Pet3ris** [comment]
The option `-p` also doesn't seem to exist anymore for `shasum` 6.02 (even on Mac).

**Comment by arr00** [comment]
#80 addresses this issue

**Comment by jflatow** [comment]
#80 has been merged
