### ISSUE TITLE
A question about COMP distribution

### ISSUE THREAD

**Issue by qiluge** [compound-finance/compound-protocol#62]
While update supply index and borrow index, you use the same compSpeed value to calculate. Will it double distribute COMP? I think it should be `compRate = borrowSpeed + supplySpeed`.

**Comment by qiluge** [comment]
Where can I find the description doc about `ComptrollerG3.sol`?

**Comment by qiluge** [comment]
`Within each market, half of the COMP is allocated to suppliers, and the other half to borrowers`.
But in your code, how to implement this? If I want to distribute 2 COMP at each block, if there is only one market, should I set `compRate = 1COMP` or `compRate = 2COMP`?

**Comment by jflatow** [comment]
Yes, you would set compRate = 1 to distribute 2 total each block. Please take future discussion like this to the Discord #development channel or [comp.xyz](https://www.comp.xyz) forum.
