### ISSUE TITLE
[Feature] Provide a "Pre-Liquidation Liquidator" which can only be called by the investor himself

### ISSUE THREAD

**Issue by michael-spengler** [compound-finance/compound-protocol#90]
Saving the investors from paying the liquidation fee when they e.g. have an own watcher running to ensure the health of their LTV ratio ...

I only found the https://compound.finance/docs/ctokens#liquidate-borrow function and the https://compound.finance/docs/ctokens#repay-borrow function. I'm looking for something like "repay-using-collateral".

I think it would be cool for investors to give them the chance to trigger the non-costly own pre-liquidation clearing before the liquidation threshold is reached.

This feature makes sense for investors who do not have the immediate liquidity to just pay back their loans in order to free their assets --> therefore I call this feature pre-liquidation liquidator.

I would be available for pair programming around this topic. And I would love to use this new feature e.g. in investment scenarios like:

https://github.com/compound-developers/compound-borrow-examples/pull/4/files#diff-c01084a9b4ef09920fc40dd8eee592e8133336f3c4f88b2574e361483ead79b2R53-R63

**Comment by arr00** [comment]
@michael-spengler This is a great idea, but not something that would be integrated directly into the compound protocol. You can very easily write a smart-contract that does *pre-liquidation* using flashloans.

**Comment by michael-spengler** [comment]
Thanks @arr00. I'll try it out. If you have any code examples which come close to this, you might let me know.
